import { Button, VerticalBox, TabWidget } from "std-widgets.slint";
import { StandardListView , TabBarImpl, LineEdit, ListView} from "std-widgets.slint";
import {TagLibrary, QuickAccess} from "controls.slint";
import { TabContext } from "context.slint";


export component ExploreWindow inherits Window {

    no-frame: true;
    // Golden Ratio Preferred
    width: 809px;
    height: 500px;

    
    HorizontalLayout 
    {
        padding: 1px;

        controlColumn := VerticalLayout
        {
            width: 309px;
            padding: 2px;
            QuickAccess {}
            Rectangle 
            {
                height: 1px;
                background: magenta;
            }
            TagLibrary {}
        }

        Rectangle
        {
            width: 1px;
            background: gray;
        }

        TabContext {}


    }
}

